"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class PullTask(object):
    __slots__ = ["timestamp", "worker_id"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.timestamp = 0
        self.worker_id = 0

    def encode(self):
        buf = BytesIO()
        buf.write(PullTask._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.timestamp, self.worker_id))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PullTask._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PullTask._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = PullTask()
        self.timestamp, self.worker_id = struct.unpack(">qq", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if PullTask in parents: return 0
        tmphash = (0xf842fe6681362d42) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if PullTask._packed_fingerprint is None:
            PullTask._packed_fingerprint = struct.pack(">Q", PullTask._get_hash_recursive([]))
        return PullTask._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

