"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from sim_signal.Result import Result as sim_signal_Result

class PushResult(object):
    __slots__ = ["timestamp", "worker_id", "result"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.timestamp = 0
        self.worker_id = 0
        self.result = sim_signal_Result()

    def encode(self):
        buf = BytesIO()
        buf.write(PushResult._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.timestamp, self.worker_id))
        assert self.result._get_packed_fingerprint() == sim_signal_Result._get_packed_fingerprint()
        self.result._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PushResult._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PushResult._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = PushResult()
        self.timestamp, self.worker_id = struct.unpack(">qq", buf.read(16))
        self.result = sim_signal_Result._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if PushResult in parents: return 0
        newparents = parents + [PushResult]
        tmphash = (0xc903aa9c1ba18f8+ sim_signal_Result._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if PushResult._packed_fingerprint is None:
            PushResult._packed_fingerprint = struct.pack(">Q", PushResult._get_hash_recursive([]))
        return PushResult._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

