"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from sim_signal.Task import Task as sim_signal_Task

class PushTask(object):
    __slots__ = ["timestamp", "worker_id", "task"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.timestamp = 0
        self.worker_id = 0
        self.task = sim_signal_Task()

    def encode(self):
        buf = BytesIO()
        buf.write(PushTask._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.timestamp, self.worker_id))
        assert self.task._get_packed_fingerprint() == sim_signal_Task._get_packed_fingerprint()
        self.task._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PushTask._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PushTask._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = PushTask()
        self.timestamp, self.worker_id = struct.unpack(">qq", buf.read(16))
        self.task = sim_signal_Task._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if PushTask in parents: return 0
        newparents = parents + [PushTask]
        tmphash = (0x52fe6681362d4128+ sim_signal_Task._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if PushTask._packed_fingerprint is None:
            PushTask._packed_fingerprint = struct.pack(">Q", PushTask._get_hash_recursive([]))
        return PushTask._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

