"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from sim_signal.Result import Result as sim_signal_Result

class ReportResult(object):
    __slots__ = ["timestamp", "result"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.timestamp = 0
        self.result = sim_signal_Result()

    def encode(self):
        buf = BytesIO()
        buf.write(ReportResult._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        assert self.result._get_packed_fingerprint() == sim_signal_Result._get_packed_fingerprint()
        self.result._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ReportResult._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ReportResult._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ReportResult()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.result = sim_signal_Result._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ReportResult in parents: return 0
        newparents = parents + [ReportResult]
        tmphash = (0xf37066b4fa3d9fb2+ sim_signal_Result._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ReportResult._packed_fingerprint is None:
            ReportResult._packed_fingerprint = struct.pack(">Q", ReportResult._get_hash_recursive([]))
        return ReportResult._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

