"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ReportResultResp(object):
    __slots__ = ["timestamp"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.timestamp = 0

    def encode(self):
        buf = BytesIO()
        buf.write(ReportResultResp._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ReportResultResp._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ReportResultResp._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ReportResultResp()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ReportResultResp in parents: return 0
        tmphash = (0x15f6c2ff87516c52) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ReportResultResp._packed_fingerprint is None:
            ReportResultResp._packed_fingerprint = struct.pack(">Q", ReportResultResp._get_hash_recursive([]))
        return ReportResultResp._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

