"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class StartNotice(object):
    __slots__ = ["timestamp", "index"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.timestamp = 0
        self.index = 0

    def encode(self):
        buf = BytesIO()
        buf.write(StartNotice._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.timestamp, self.index))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != StartNotice._get_packed_fingerprint():
            raise ValueError("Decode error")
        return StartNotice._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = StartNotice()
        self.timestamp, self.index = struct.unpack(">qq", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if StartNotice in parents: return 0
        tmphash = (0x84faf50ddc2ba1cb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if StartNotice._packed_fingerprint is None:
            StartNotice._packed_fingerprint = struct.pack(">Q", StartNotice._get_hash_recursive([]))
        return StartNotice._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

